fail_on_violations: true
ruby:
  enabled: true
  config_file: .rubocop.yml
eslint:
  enabled: false
  config_file: .eslintrc.yml
scss:
  enabled: true
  config_file: .scss-lint.yml
jshint:
  enabled: false
