# Disable defaults
AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "script/**/*"
    - "tmp/**/*"
    - "uploads/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnneededCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - db/migrate/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 110
  IgnoredPatterns:
    # Test descriptors
    - ^\s*(describe|it|context|scenario) ".+" do$

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/decorators/**/*"
    - "app/serializers/**/*"
    - db/migrate/*

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - to
    - not_to
    - require
    - raise
    - puts
    - validates # Sometimes this is called in a with_options block, confusing the cop.
    - class_eval
  Exclude:
    - Gemfile
    - db/migrate/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler:
  Enabled: true

Rails:
  Enabled: true

Rails/Output:
  Enabled: true
  Exclude:
    - db/migrate/**/*

Rails/SkipsModelValidations:
  Enabled: false

# This is generally bad advice, defaults are often set in code.
Rails/NotNullColumn:
  Enabled: false
